In [1]:
# Author        : Cow Cheng
# Date          : 30/06/2024
# Description   : Creating edgelist for lanes property of edge from the raw edges information

In [2]:
import os
from pathlib import Path

ROOT_DIR = Path(os.getcwd()).parent.parent.absolute().__str__()

In [3]:
import pandas as pd

edges_df = pd.read_csv(filepath_or_buffer=f"{ROOT_DIR}/data/raw/osm_edges_info.csv")
edges_df

,u,v,key,osmid,oneway,lanes,name,highway,reversed,length,junction,bridge,ref,maxspeed,tunnel,access,service,area,geometry
0,33004487,10813125727,0,102506130,True,3.0,彌敦道 Nathan Road,primary,False,48.365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1710946 22.310275, 114.1710536..."
1,33004487,9125470653,0,102506142,True,2.0,眾坊街 Public Square Street,secondary,False,1.845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1710946 22.310275, 114.1710767..."
2,33004488,6357916699,0,102640426,True,3.0,彌敦道 Nathan Road,primary,False,11.143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1707174 22.3129765, 114.170737..."
3,33004488,1151084822,0,250489279,True,2.0,窩打老道 Waterloo Road,primary,False,10.668,intersection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1707174 22.3129765, 114.170620..."
4,34971941,332248875,0,493744605,True,2.0,加士居道天橋 Gascoigne Road Flyover,trunk,False,43.118,NaN,yes,5.0,50.0,NaN,NaN,NaN,NaN,"LINESTRING (114.1673899 22.3106905, 114.167470..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7053,11880893092,11880893093,0,987256892,False,1.0,NaN,service,False,7.312,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.1716736 22.3111966, 114.171624..."
7054,11880893092,9125470644,0,987256892,False,1.0,NaN,service,True,7.362,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.1716736 22.3111966, 114.171708..."
7055,11880893093,11880893092,0,987256892,False,1.0,NaN,service,True,7.312,NaN,NaN,NaN,NaN,NaN,NaN,driveway,NaN,"LINESTRING (114.171624 22.3112437, 114.1716736..."
7056,11880893105,6521288995,0,150801664,False,NaN,石壁道 Cliff Road,residential,False,2.668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1718521 22.3104017, 114.171830..."
7057,11880893105,4571243168,0,150801664,False,NaN,石壁道 Cliff Road,residential,True,2.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (114.1718521 22.3104017, 114.171863..."

In [4]:
edges_df = edges_df.loc[:, ["u", "v", "lanes"]]
edges_df

                u            v  lanes
0        33004487  10813125727    3.0
1        33004487   9125470653    2.0
2        33004488   6357916699    3.0
3        33004488   1151084822    2.0
4        34971941    332248875    2.0
...           ...          ...    ...
7053  11880893092  11880893093    1.0
7054  11880893092   9125470644    1.0
7055  11880893093  11880893092    1.0
7056  11880893105   6521288995    NaN
7057  11880893105   4571243168    NaN

[7058 rows x 3 columns]

In [5]:
edges_list = edges_df.values.tolist()
for edge in edges_list:
    edge[0] = int(edge[0])
    edge[1] = int(edge[1])
    if str(edge[2]) == "nan":
        edge[2] = -1.0
edges_list

[[33004487, 10813125727, 3.0],
 [33004487, 9125470653, 2.0],
 [33004488, 6357916699, 3.0],
 [33004488, 1151084822, 2.0],
 [34971941, 332248875, 2.0],
 [245088212, 5135751883, 3.0],
 [245088214, 8795975506, 4.0],
 [274242693, 332243940, 2.0],
 [274242694, 4501965596, 2.0],
 [274242695, 3230279839, 2.0],
 [274242705, 274242708, 2.0],
 [274243013, 274243014, 3.0],
 [274243014, 4773727051, 3.0],
 [274243015, 8446511187, 3.0],
 [274243016, 1181846034, 2.0],
 [274243016, 8406879034, 2.0],
 [274243017, 332242393, 2.0],
 [274243018, 10566992992, 2.0],
 [274243083, 332233448, 4.0],
 [274243086, 5103661134, 2.0],
 [274243086, 5103661131, 2.0],
 [275908396, 10566992979, 3.0],
 [275909256, 6374553590, 3.0],
 [275909450, 7305838958, 2.0],
 [275909450, 7305838955, 2.0],
 [275935771, 7600185392, 2.0],
 [275944916, 4773693609, 2.0],
 [275945320, 9766361634, 2.0],
 [275945418, 3230274782, 2.0],
 [275945418, 9766365660, 2.0],
 [275945538, 11235236460, 3.0],
 [275945538, 10565387068, 2.0],
 [275945653, 10726301482, 2.0],
 [275945763, 10211498580, 1.0],
 [275945763, 3919865758, 2.0],
 [276372857, 6357916383, 2.0],
 [276372857, 1151084911, 3.0],
 [276373355, 6357916373, 3.0],
 [276377951, 11235236461, 2.0],
 [278948068, 1168316016, 2.0],
 [278948068, 6370253655, 2.0],
 [278948235, 10786928815, 3.0],
 [278948607, 6271340027, 2.0],
 [278948608, 1184307108, 1.0],
 [278948608, 332254414, 1.0],
 [278948609, 5255598058, -1.0],
 [278948759, 2640738083, 1.0],
 [278948832, 278948833, -1.0],
 [278948833, 5255598053, -1.0],
 [278948926, 6605085116, 2.0],
 [278948926, 5012933247, 2.0],
 [278948927, 5255598054, 2.0],
 [278948927, 5255598074, -1.0],
 [278948933, 439179847, -1.0],
 [278948934, 8044314666, -1.0],
 [278948999, 8044314690, -1.0],
 [278948999, 278949000, -1.0],
 [278949000, 278949001, -1.0],
 [278949000, 278948999, -1.0],
 [278949001, 278949000, -1.0],
 [279076776, 8764628282, 2.0],
 [279076776, 6550920169, 2.0],
 [288991082, 9893206659, 1.0],
 [288991083, 1172166327, 1.0],
 [288991084, 6777002698, 2.0],
 [288991123, 5029510785, 2.0],
 [288991123, 1962192579, 2.0],
 [288991127, 1962191597, 2.0],
 [288991127, 5029510779, 2.0],
 [288991129, 6052460354, 2.0],
 [288991129, 1962191505, 2.0],
 [288991131, 5118308284, 2.0],
 [288991131, 1172166329, 2.0],
 [288991132, 5118308285, 2.0],
 [288991132, 5118308284, 2.0],
 [288991202, 1172166326, 3.0],
 [288991202, 5029495350, -1.0],
 [288991212, 1295862825, 3.0],
 [288991212, 493883921, 3.0],
 [288991212, 1172166356, -1.0],
 [288991213, 1295862822, 3.0],
 [288991213, 1295862825, 3.0],
 [288991214, 332232638, 3.0],
 [288991214, 1295862839, 3.0],
 [288991218, 1962192639, 2.0],
 [288991218, 1962192676, 2.0],
 [288991218, 6266394644, 2.0],
 [288991219, 7154099552, 2.0],
 [288991219, 5029510784, 2.0],
 [288991219, 7154099554, -1.0],
 [288991220, 5118308280, 2.0],
 [288991220, 5029510780, 2.0],
 [288991221, 1962191716, 2.0],
 [288991221, 5118308280, 2.0],
 [288991222, 5029510778, 2.0],
 [288991222, 1962191597, 2.0],
 [288991223, 5118308283, 2.0],
 [288991223, 5118308286, 2.0],
 [288991224, 8396898511, 2.0],
 [288991224, 8081586137, 2.0],
 [288991224, 6277201384, -1.0],
 [288991681, 6176166200, 2.0],
 [288991681, 6176166201, 2.0],
 [288991682, 5118308267, 2.0],
 [288991682, 7597784320, -1.0],
 [288991682, 6039377373, 2.0],
 [288991740, 2868161557, 4.0],
 [288991741, 6364822864, 4.0],
 [288991742, 2086704742, 4.0],
 [288991742, 1182677912, 4.0],
 [288991776, 3230279162, 3.0],
 [288991777, 288991776, 3.0],
 [288991796, 1168066109, 3.0],
 [288991796, 9553739297, 3.0],
 [288991859, 4353561377, 2.0],
 [288991960, 288991859, 2.0],
 [288991961, 1640472777, 2.0],
 [288991961, 4858602289, 3.0],
 [288992106, 1640472750, 2.0],
 [288992206, 1640472741, 2.0],
 [288994875, 1640472834, -1.0],
 [288994875, 6886397805, 2.0],
 [288994882, 5103568431, 2.0],
 [288994882, 3200153661, 2.0],
 [288994965, 7859225560, 2.0],
 [288995086, 288995087, 2.0],
 [288995087, 7859225566, 2.0],
 [288995158, 3696283366, 2.0],
 [288995217, 4858447071, 2.0],
 [288996266, 7605392237, 2.0],
 [288996266, 7605392232, 2.0],
 [288996632, 288994882, 2.0],
 [288996657, 6886397800, 2.0],
 [289337490, 7575216225, 3.0],
 [289337490, 4858447073, 2.0],
 [308473171, 3230274026, -1.0],
 [308473171, 3230274006, 2.0],
 [308473172, 3230274170, 3.0],
 [308473172, 3230274041, 2.0],
 [308473173, 3230274023, 3.0],
 [308473173, 3230274192, 2.0],
 [308473175, 3230274366, 1.0],
 [308473175, 3230274296, 1.0],
 [308473176, 11134510106, 2.0],
 [308473177, 1183092765, 2.0],
 [308473177, 1151084890, 3.0],
 [308473178, 11134374501, 3.0],
 [308473179, 11134374504, 1.0],
 [308473179, 11134374500, -1.0],
 [308473179, 11134374497, 1.0],
 [308473180, 6260814403, 3.0],
 [308473180, 10804883515, 3.0],
 [308473181, 3230277085, 2.0],
 [308473182, 3230277492, 3.0],
 [308473182, 3230277353, 2.0],
 [308473183, 3230277355, 3.0],
 [308473183, 3230277483, 2.0],
 [308473185, 3230277719, 1.0],
 [308473185, 3230277610, 2.0],
 [308473186, 10825885939, 2.0],
 [308473186, 10181859559, -1.0],
 [308473186, 3230278485, -1.0],
 [308473187, 3230278507, 1.0],
 [308473188, 3230278501, 2.0],
 [308473188, 11235236463, 3.0],
 [308473189, 11196264030, 4.0],
 [308473190, 3230280848, 4.0],
 [308473190, 3230280999, 3.0],
 [308473191, 3230280976, 4.0],
 [308473191, 6364821073, 3.0],
 [308473192, 3230281110, 5.0],
 [308473193, 7205061372, 1.0],
 [308473193, 7205061371, 1.0],
 [308473195, 10250932206, 3.0],
 [308473419, 4501975098, 3.0],
 [308473420, 11232787248, 1.0],
 [308473420, 11134510116, 3.0],
 [308473422, 9953781642, 2.0],
 [308473422, 9953781649, 3.0],
 [308473423, 3176514544, 3.0],
 [308473424, 7983295859, 3.0],
 [308473424, 1151084860, 3.0],
 [308473425, 9067018578, 4.0],
 [308473426, 10825885963, 1.0],
 [308473427, 3230280089, 1.0],
 [308473429, 4862720941, 1.0],
 [308473429, 11235236471, 2.0],
 [308473546, 11248659125, 1.0],
 [308473546, 1178971365, 1.0],
 [308473546, 7205249277, 1.0],
 [316731588, 10864964066, -1.0],
 [316731590, 8789236514, -1.0],
 [316731591, 8789236510, 4.0],
 [316731592, 11406997370, -1.0],
 [316731592, 4292132285, -1.0],
 [316731592, 4292143906, -1.0],
 [331258075, 1168315954, 2.0],
 [331258075, 6374553575, 2.0],
 [331258761, 7257383508, 3.0],
 [331258761, 7257383490, 2.0],
 [331258761, 4773779469, 1.0],
 [331258764, 991294650, 1.0],
 [331269944, 332251255, 3.0],
 [331269982, 7242599215, 2.0],
 [331269982, 6236308354, 3.0],
 [331271265, 4773779481, 2.0],
 [331271265, 4773716027, 2.0],
 [331271928, 2389070841, 2.0],
 [332227468, 4858602284, 1.0],
 [332227468, 6364822991, 4.0],
 [332227469, 332227468, 3.0],
 [332227470, 332227469, 2.0],
 [332227471, 9893504824, 2.0],
 [332228049, 332233734, 2.0],
 [332228049, 11229660893, 2.0],
 [332228052, 5133915668, 2.0],
 [332228052, 5133915667, 1.0],
 [332228053, 4501965600, 2.0],
 [332228053, 4501965601, 2.0],
 [332228054, 5133915669, 2.0],
 [332228055, 332228056, 2.0],
 [332228056, 1182677867, 2.0],
 [332228056, 332228057, 2.0],
 [332228057, 1640472754, 1.0],
 [332228057, 6886392425, 2.0],
 [332228058, 4858594757, 2.0],
 [332228059, 6886392427, 3.0],
 [332228061, 7257383509, 2.0],
 [332230218, 332228059, 3.0],
 [332230894, 332227469, 2.0],
 [332230895, 332230894, 2.0],
 [332231811, 5118069110, 2.0],
 [332231811, 6364822869, 2.0],
 [332231898, 332231899, 5.0],
 [332231899, 2868161561, 3.0],
 [332231899, 2868161562, 2.0],
 [332231922, 1182677790, 3.0],
 [332231923, 332231922, 3.0],
 [332231924, 332231923, 3.0],
 [332231925, 332231924, 4.0],
 [332232288, 2868161559, 2.0],
 [332232290, 1182677772, 2.0],
 [332232291, 9553739289, 2.0],
 [332232291, 1182677796, 2.0],
 [332232292, 288991961, 4.0],
 [332232293, 332232292, 4.0],
 [332232294, 6984911314, 2.0],
 [332232295, 6984911302, 2.0],
 [332232638, 1172166308, 3.0],
 [332232638, 288991214, 3.0],
 [332232732, 1956604873, 3.0],
 [332232732, 1172166429, 2.0],
 [332232732, 1956604863, 3.0],
 [332232763, 332232764, 2.0],
 [332232763, 6777002695, 2.0],
 [332232763, 6776978979, -1.0],
 [332232764, 332232765, 2.0],
 [332232764, 332232763, 2.0],
 [332232765, 332232766, 2.0],
 [332232765, 332232764, 2.0],
 [332232766, 5118308287, 2.0],
 [332232766, 332232765, 2.0],
 [332233250, 2868161565, 1.0],
 [332233250, 5118069109, 4.0],
 [332233253, 1168183739, 4.0],
 [332233448, 9553739296, 2.0],
 [332233448, 8154269374, 2.0],
 [332233449, 9553739295, 2.0],
 [332233450, 9553739291, 2.0],
 [332233452, 5054347008, 4.0],
 [332233734, 6776978971, 2.0],
 [332234423, 332234424, 2.0],
 [332234424, 9553982032, 2.0],
 [332234425, 5118039272, 1.0],
 [332234452, 332234425, 1.0],
 [332235143, 9553982035, 3.0],
 [332236247, 11242686010, 2.0],
 [332236248, 3230279914, 2.0],
 [332236250, 332236251, 2.0],
 [332236251, 332236252, 2.0],
 [332236252, 9553739290, 2.0],
 [332236302, 332236591, 2.0],
 [332236303, 5118039270, 2.0],
 [332236564, 4944491510, 3.0],
 [332236591, 5118039267, 2.0],
 [332236658, 3230278791, 2.0],
 [332236659, 493175666, 2.0],
 [332236871, 4944491509, 3.0],
 [332237002, 332237036, 3.0],
 [332237036, 332236871, 3.0],
 [332237192, 332237262, 2.0],
 [332237199, 6374553508, 2.0],
 [332237238, 332237192, 2.0],
 [332237262, 4773727049, 3.0],
 [332237288, 3270208461, 2.0],
 [332238310, 11129305619, 3.0],
 [332238480, 6389190616, 2.0],
 [332238481, 11214989179, 2.0],
 [332238481, 11214989167, 2.0],
 [332239185, 5133960459, 2.0],
 [332239185, 1180686912, 3.0],
 [332240179, 11453018971, 3.0],
 [332240248, 6389233142, 2.0],
 [332240697, 1181846062, 1.0],
 [332240700, 4773779472, 1.0],
 [332241860, 5020696807, 1.0],
 [332241861, 10566992988, 1.0],
 [332241861, 10566992986, 2.0],
 [332241870, 1172757618, 2.0],
 [332241870, 332243716, 2.0],
 [332241887, 8559094354, 1.0],
 [332241978, 1181846107, 1.0],
 [332241978, 7257383506, 1.0],
 [332241980, 7257383504, 1.0],
 [332242040, 6984393973, 2.0],
 [332242040, 6984393970, 1.0],
 [332242116, 4773779436, 2.0],
 [332242333, 6576843537, 3.0],
 [332242333, 7159249733, 1.0],
 [332242336, 1161863870, 1.0],
 [332242353, 4773779431, 4.0],
 [332242393, 274243018, 2.0],
 [332242579, 6370140256, 3.0],
 [332242579, 7242599236, 3.0],
 [332242620, 1181846148, -1.0],
 [332242620, 4123241553, 2.0],
 [332242753, 10848289257, -1.0],
 [332242753, 1178971331, 2.0],
 [332242754, 332251620, 2.0],
 [332242754, 332242753, 2.0],
 [332242755, 5035288921, 1.0],
 [332242755, 1178971377, 3.0],
 [332242765, 332243937, 2.0],
 [332243000, 6264275960, 2.0],
 [332243002, 332253240, 3.0],
 [332243003, 288991796, 4.0],
 [332243003, 1168066104, 3.0],
 [332243005, 4860492619, 2.0],
 [332243007, 7205257472, 2.0],
 [332243088, 6357916689, 2.0],
 [332243088, 6063179965, 2.0],
 [332243513, 8273466961, 3.0],
 [332243571, 332246717, 2.0],
 [332243585, 4501974987, 2.0],
 [332243716, 332241870, 2.0],
 [332243716, 332241978, 2.0],
 [332243937, 7257383515, 2.0],
 [332243938, 7388719094, 2.0],
 [332243939, 274242693, 2.0],
 [332243940, 3230277782, 2.0],
 [332243941, 7388719090, 2.0],
 [332244016, 8272842740, 1.0],
 [332244018, 3696262782, 1.0],
 [332244341, 274243083, 4.0],
 [332246270, 6176174000, 4.0],
 [332246273, 1168380690, 2.0],
 [332246717, 34971941, 2.0],
 [332246756, 5133754167, 2.0],
 [332247607, 6611651275, 1.0],
 [332247608, 332248687, 2.0],
 [332248212, 332248213, 2.0],
 [332248213, 629161529, 2.0],
 [332248214, 6702444348, 2.0],
 [332248685, 332248700, 2.0],
 [332248686, 5118308275, 2.0],
 [332248687, 332248686, 2.0],
 [332248700, 332243513, 3.0],
 [332248875, 332248821, 1.0],
 [332250570, 10786928832, 2.0],
 [332251015, 3230283954, 2.0],
 [332251015, 1168183637, 2.0],
 [332251063, 5103661127, 3.0],
 [332251063, 5103661126, 3.0],
 [332251094, 11181151128, 2.0],
 [332251094, 4860492620, 2.0],
 [332251253, 332251620, 2.0],
 [332251253, 11178396848, -1.0],
 [332251253, 332242753, -1.0],
 [332251254, 332251484, 2.0],
 [332251254, 3391012792, 3.0],
 [332251255, 9067018573, 3.0],
 [332251256, 7205249279, 1.0],
 [332251256, 7207625693, 1.0],
 [332251257, 332251256, 1.0],
 [332251257, 10181839350, 2.0],
 [332251373, 1182677910, 4.0],
 [332251374, 3230283899, 5.0],
 [332251374, 3230283560, 4.0],
 [332251375, 9067018588, 4.0],
 [332251375, 9067018571, 3.0],
 [332251376, 7207625692, 3.0],
 [332251377, 3696264071, 3.0],
 [332251377, 10198945171, 2.0],
 [332251377, 10181839356, 1.0],
 [332251378, 3691165231, 3.0],
 [332251484, 10203538055, 2.0],
 [332251484, 1442088610, 2.0],
 [332251500, 9135398607, 4.0],
 [332251605, 3391012791, 5.0],
 [332251620, 6236308350, 2.0],
 [332251664, 332251373, 4.0],
 [332251664, 11177196758, 2.0],
 [332251667, 7454080527, 1.0],
 [332251667, 5133880779, 4.0],
 [332251683, 332251682, -1.0],
 [332251828, 11134374487, 3.0],
 [332252247, 7597823394, 3.0],
 [332252247, 1182950283, 2.0],
 [332253240, 1168315922, 3.0],
 [332253240, 8438621459, 1.0],
 [332253310, 3230275941, -1.0],
 [332253310, 3230275869, 3.0],
 [332253311, 3230276002, 3.0],
 [332253311, 3230275952, 3.0],
 [332253312, 3230275924, 3.0],
 [332253312, 3230276003, 1.0],
 [332253313, 3230276216, 1.0],
 [332253329, 7159812414, 2.0],
 [332253329, 1185400641, 1.0],
 [332253331, 10825885941, 1.0],
 [332253333, 8192075924, 1.0],
 [332253494, 6880235602, 2.0],
 [332253494, 4501974988, 2.0],
 [332253631, 3230274239, 3.0],
 [332254414, 4355051555, -1.0],
 [332254415, 3691187062, 1.0],
 [332254415, 1162875764, 2.0],
 [334647674, 2861669114, 2.0],
 [334647674, 11104977107, 3.0],
 [334647889, 2861666795, 3.0],
 [334647890, 11104980151, 3.0],
 [334647891, 2861666800, 3.0],
 [334647892, 2861669103, 3.0],
 [334647893, 334647894, 3.0],
 [334647894, 2861669109, 3.0],
 [334647895, 11104980142, 4.0],
 [334647896, 11104980135, 4.0],
 [334647897, 4502010708, 4.0],
 [334647899, 334652200, 3.0],
 [334648400, 1168315957, 1.0],
 [334648405, 334648629, 1.0],
 [334648625, 6989122616, 3.0],
 [334648625, 1168315919, 2.0],
 [334648626, 6357916691, 3.0],
 [334648627, 1168315967, 1.0],
 [334648629, 334648627, 1.0],
 [334648722, 334651133, 3.0],
 [334648723, 334651132, 3.0],
 [334648727, 2861669101, 2.0],
 [334649581, 11081087759, 2.0],
 [334649727, 334649852, 3.0],
 [334649728, 8767974619, 3.0],
 [334649729, 2868161551, 1.0],
 [334649849, 334650280, 2.0],
 [334649850, 4501965609, 2.0],
 [334649851, 2866714638, 2.0],
 [334649851, 2866714639, 1.0],
 [334649852, 334649851, 3.0],
 [334650236, 11104980140, 4.0],
 [334650280, 2866714635, 2.0],
 [334650280, 2866714634, 1.0],
 [334650313, 339053515, 1.0],
 [334650313, 339053461, 2.0],
 [334650570, 1172166386, 3.0],
 [334650572, 334650573, 1.0],
 [334650573, 334650574, 1.0],
 [334650574, 9125470648, 1.0],
 [334650575, 1168315927, 1.0],
 [334650654, 9125470651, 2.0],
 [334650656, 1172166367, 2.0],
 [334650656, 7553815435, 3.0],
 [334650889, 334650890, 3.0],
 [334650890, 334650891, 2.0],
 [334650891, 6370217679, 2.0],
 [334650892, 334650893, 2.0],
 [334650893, 4501965605, 2.0],
 [334650906, 7859225563, 2.0],
 [334650907, 2868161575, 2.0],
 [334650908, 8767974621, 3.0],
 [334651084, 2868161570, 1.0],
 [334651084, 2868161571, 2.0],
 [334651129, 334651084, 3.0],
 [334651130, 7539621741, 1.0],
 [334651131, 7270937151, 1.0],
 [334651132, 334648722, 3.0],
 [334651133, 11105007273, 3.0],
 [334651138, 2868161552, 1.0],
 [334651139, 2868161550, 1.0],
 [334651140, 11104975395, 1.0],
 [334651141, 11104975391, 3.0],
 [334651141, 11104975394, 1.0],
 [334651192, 8909807442, 2.0],
 [334651192, 7605392237, 2.0],
 [334651193, 11462479066, 2.0],
 [334651193, 7605409499, 1.0],
 [334651194, 334651193, 1.0],
 [334651195, 5052279540, 1.0],
 [334651195, 6776978974, 2.0],
 [334651201, 334651131, 1.0],
 [334651203, 334651201, 1.0],
 [334652024, 334652025, 3.0],
 [334652025, 2832941849, 3.0],
 [334652026, 11104977129, 3.0],
 [334652027, 11104980131, 3.0],
 [334652029, 11104980139, 5.0],
 [334652030, 11104980143, 5.0],
 [334652032, 11104980146, 3.0],
 [334652033, 2861669108, 3.0],
 [334652034, 334652035, 3.0],
 [334652035, 334652036, 3.0],
 [334652036, 334652037, 3.0],
 [334652037, 334652038, 3.0],
 [334652038, 339053444, 3.0],
 [334652200, 11104977130, 3.0],
 [334652201, 334652202, 3.0],
 [334652202, 2832941850, 3.0],
 [334653504, 334650908, 3.0],
 [334653511, 2868161573, 2.0],
 [339050813, 8766021731, 3.0],
 [339050887, 7553034785, 1.0],
 [339050887, 339050888, 2.0],
 [339050888, 339050889, 2.0],
 [339050889, 2861669102, 2.0],
 [339050890, 339050891, 2.0],
 [339050891, 339050892, 2.0],
 [339050892, 339050893, 2.0],
 [339050893, 2861669105, 2.0],
 [339050894, 339050895, 2.0],
 [339050895, 339050896, 2.0],
 [339050896, 339050897, 2.0],
 [339050897, 339050898, 2.0],
 [339050898, 339050899, 2.0],
 [339050899, 339050900, 2.0],
 [339050900, 5436700704, 2.0],
 [339050901, 2866714610, 2.0],
 [339050902, 339050903, 2.0],
 [339050903, 6052450981, 2.0],
 [339050904, 339050905, 2.0],
 [339050905, 339050906, 2.0],
 [339050906, 5118308277, 1.0],
 [339050906, 5118308279, 1.0],
 [339050907, 339050908, 1.0],
 [339050908, 339050909, 1.0],
 [339050909, 9125470649, 1.0],
 [339051476, 339051477, 2.0],
 [339051477, 339051478, 2.0],
 [339051478, 339051479, 2.0],
 [339051479, 339051480, 2.0],
 [339051480, 339051481, 2.0],
 [339051481, 339051482, 2.0],
 [339051482, 11242686018, 2.0],
 [339051538, 339051539, 2.0],
 [339051539, 339051540, 2.0],
 [339051540, 11242686024, 2.0],
 [339051541, 11242686009, 2.0],
 [339051592, 2866714604, 2.0],
 [339051593, 339051594, 2.0],
 [339051594, 339052028, 1.0],
 [339051594, 339052027, 1.0],
 [339051595, 339051596, 2.0],
 [339051596, 339051597, 2.0],
 [339051597, 339051598, 2.0],
 [339051598, 339051599, 2.0],
 [339051599, 339051600, 2.0],
 [339051600, 339051601, 2.0],
 [339051601, 2861669111, 2.0],
 [339051602, 11104980147, 2.0],
 [339051767, 339051593, -1.0],
 [339051768, 339051767, -1.0],
 [339051769, 339051768, -1.0],
 [339051784, 339051769, -1.0],
 [339051785, 339051784, -1.0],
 [339051786, 4971724758, -1.0],
 [339051995, 2866714633, 2.0],
 [339051996, 2866714633, 1.0],
 [339051997, 8766003550, 2.0],
 [339051998, 339051997, 2.0],
 [339051999, 2861669104, 2.0],
 [339052000, 2861666798, 1.0],
 [339052001, 339052000, 1.0],
 [339052027, 339051595, 2.0],
 [339052028, 339052029, 1.0],
 [339052029, 339052030, 1.0],
 [339052030, 339052031, 1.0],
 [339052031, 2866714626, 1.0],
 [339052032, 339051996, 1.0],
 [339052060, 11104980152, 2.0],
 [339053444, 2861666791, 3.0],
 [339053461, 1640472727, 2.0],
 [339053462, 339052060, 2.0],
 [339053474, 11104975397, 2.0],
 [339053482, 2866714620, 2.0],
 [339053515, 2866714603, 1.0],
 [339053516, 5333519688, 1.0],
 [339053606, 2866714631, 1.0],
 [339053606, 1168315989, 1.0],
 [339053607, 2866714615, 1.0],
 [339053608, 2866714601, 1.0],
 [339053635, 2866714495, 2.0],
 [339053698, 2866714602, 1.0],
 [339053699, 2866714618, 1.0],
 [339053700, 2866714625, 1.0],
 [339053701, 2866714630, 1.0],
 [339054218, 9678646965, 2.0],
 [339054219, 9772967563, 2.0],
 [339054219, 9773097328, 2.0],
 [339054265, 4773693583, 2.0],
 [339054265, 4773693580, 2.0],
 [339054267, 4773693576, 3.0],
 [339054322, 6389190615, 2.0],
 [339054322, 4353541537, 2.0],
 [339054415, 9197567330, 3.0],
 [339054415, 339054265, 3.0],
 [339054417, 10290775981, 2.0],
 [339054417, 8912728888, 1.0],
 [339054418, 4773331331, 1.0],
 [339054470, 6895725701, 2.0],
 [339054471, 339054470, 2.0],
 [339054472, 6991262053, 2.0],
 [339054473, 339054472, 2.0],
 [339054474, 4773693593, 2.0],
 [339054475, 1152803603, 2.0],
 [339054476, 339054475, 2.0],
 [412685610, 4335274775, 3.0],
 [412685610, 332242754, 2.0],
 [412685611, 6990193881, 2.0],
 [419752768, 332251063, 3.0],
 [419752768, 3391012787, 3.0],
 [419763802, 493178393, 1.0],
 [420028543, 6389233143, 2.0],
 [420028545, 10786928860, -1.0],
 [420028546, 6680793616, 1.0],
 [420028546, 1178971337, 1.0],
 [439179845, 8044314673, -1.0],
 [439179846, 439179845, -1.0],
 [439179847, 8044314665, -1.0],
 [439179847, 3691187055, -1.0],
 [439179852, 1184307124, -1.0],
 [439179852, 6605085116, -1.0],
 [439180903, 5020395154, 2.0],
 [439180903, 5118402531, 2.0],
 [439180917, 5020395132, 2.0],
 [439180917, 7207551573, 2.0],
 [439989637, 8044314778, 2.0],
 [439989637, 8044314775, 2.0],
 [439989638, 439989639, 2.0],

In [6]:
with open(f"{ROOT_DIR}/data/training/node2vec/lanes.el", "w") as f:
    for edge in edges_list:
        f.write(f"{edge[0]} {edge[1]} {edge[2]}\n")